#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Holberton School" when queried
#++    at the root with a curl GET request.

apt-get update
apt-get install -y nginx

# Create a default index.html file containing "Hello World!"
echo "Hello World!" > /usr/share/nginx/html/index.html

# Check if nginx is already running, if not start it
if ! pgrep -x "nginx" > /dev/null
then
    /usr/sbin/nginx
fi

# Check if nginx is listening on port 80, if not restart it
if ! nc -z localhost 80
then
    killall nginx
    /usr/sbin/nginx
fi

